export declare const loadMoreButton: string;
export declare const node: string;
export declare const nodeDirty: string;
export declare const nodeFocused: string;
export declare const nodeIconWrapper: string;
export declare const nodeLabel: string;
export declare const nodeRemoved: string;
export declare const pageTreeContainer: string;
export declare const pageTreeToolbarOriginal: string;
export declare const panel: string;
export declare const tabsContent: string;
export declare const tabsPanel: string;
export declare const toolbar: string;
export declare const toolbarButtons: string;
export declare const toolbarSearch: string;
export declare const toolbarSearchClearButton: string;
export declare const toolbarSearchInput: string;
export declare const toolbarSearchNoResults: string;

declare const ClassNames: {
  "loadMoreButton": string;
  "node": string;
  "nodeDirty": string;
  "nodeFocused": string;
  "nodeIconWrapper": string;
  "nodeLabel": string;
  "nodeRemoved": string;
  "pageTreeContainer": string;
  "pageTreeToolbarOriginal": string;
  "panel": string;
  "tabsContent": string;
  "tabsPanel": string;
  "toolbar": string;
  "toolbarButtons": string;
  "toolbarSearch": string;
  "toolbarSearchClearButton": string;
  "toolbarSearchInput": string;
  "toolbarSearchNoResults": string;
};
export default ClassNames;